### ISSUE TITLE
Is there a way to support `httpGeneratedImagesPath` option like grunt-contrib-compass?

### ISSUE THREAD

**Issue by imsobear** [appleboy/gulp-compass#37]
Generally, we write **compass sprite** code like this in our `src` directory:

``` sass
@import "icons/*.png";

.icon-hom {
  @include icons-sprite(home);
}
```

and it will be compiled to this:

``` css
.icon-home, .icon-tools, .icon-heart {
  background: url(../../../src/p/home/images/icons-s019adab402.png) no-repeat;
}

.icon-home {
  background-position:0 -465px;
}
```

Did you notice the `background-url`? It's relative path, but we also need an absolute path in production. 

And with **grunt-contrib-compass**, It has a `httpGeneratedImagesPath` option to support this, you can get this option in [here](https://github.com/gruntjs/grunt-contrib-compass#httpgeneratedimagespath).

So, Is there a way to support `httpGeneratedImagesPath` option like grunt-contrib-compass?

Thanks for your reply!
